version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:7.10
      environment:
        APP_ENV: testing
    # - image: circleci/postgres:9.6
    #   environment:
    #     POSTGRES_DB: teste_db
    #     POSTGRES_USER: teste_usuario
    #     POSTGRES_PASSWORD: cG6uJNyPmvQ5AEs6Lx6X
    steps:
    - checkout
    - add_ssh_keys
    - restore_cache:
        keys:
        - node-v1-{{ checksum "package.json" }}
        - node-v1-
    - run:
        name: Npm Install
        command: npm install
    - save_cache:
        key: node-v1-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: Build Frontend
        command: echo "TODO"
    - run:
        name: Test Frontend
        command: echo "TODO"
    - run:
        name: Build Backend
        command: echo "TODO"
    - run:
        name: Test Backend
        command: echo "TODO"
  deployment:
    working_directory: ~/repo
    docker:
    - image: circleci/node:7.10
    environment:
      BASH_ENV: ~/.bashrc
      HEROKU_APP_NAME: "gsw-challenge-app"
    steps:
    - checkout
    - run:
        name: Setup Heroku
        command: bash ~/repo/.circleci/setup-heroku.sh
    - run:
        name: Add Heroku to known_hosts
        command: ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
    - run:
        name: Deploy Master to Heroku
        command: |
          heroku git:remote -a $HEROKU_APP_NAME
          git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
workflows:
  version: 2
  build_release:
    jobs:
    - build
    - deployment:
        requires:
        - build
        filters:
          branches:
            only:
            - master