version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.15.2
      environment:
        APP_ENV: testing
    # - image: circleci/postgres:9.6
    #   environment:
    #     POSTGRES_DB: teste_db
    #     POSTGRES_USER: teste_usuario
    #     POSTGRES_PASSWORD: cG6uJNyPmvQ5AEs6Lx6X
    steps:
    - checkout
    - add_ssh_keys
    - run:
        name: Npm Install
        command: npm install
        working_directory: ~/repo/front
    - run:
        name: Test Frontend
        command: export CI=true && npm run test -- --env=jsdom
        working_directory: ~/repo/front
    - run:
        name: Build Frontend Front
        command: npm run build -- --prod
        working_directory: ~/repo/front
    - run:
        name: Npm Install Api
        command: npm install
        working_directory: ~/repo/api
    - run:
        name: Build Backend
        command: npm run build
        working_directory: ~/repo/api
    - run:
        name: Test Backend
        command: npm run test
        working_directory: ~/repo/api
  deployment:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.15.2
    environment:
      BASH_ENV: ~/.bashrc
      HEROKU_APP_NAME: "gsw-challenge-app"
    steps:
    - checkout
    - run:
        name: Setup Heroku
        command: bash ~/repo/.circleci/setup-heroku.sh
    - run:
        name: Setup Heroku .netrc
        command: |
          cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
          EOF
    - run:
        name: Add Heroku to known_hosts
        command: ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
    - run:
        name: Deploy Master to Heroku
        command: |
          heroku git:remote -a $HEROKU_APP_NAME
          git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
workflows:
  version: 2
  build_release:
    jobs:
    - build
    - deployment:
        requires:
        - build
        filters:
          branches:
            only:
            - master