export const ADD_CONVERSION_PENDING = "ADD_CONVERSION_PENDING";
export const ADD_CONVERSION_SUCCESS = "ADD_CONVERSION_SUCCESS";
export const ADD_CONVERSION_ERROR = "ADD_CONVERSION_ERROR";

export const FETCH_CONVERSIONS_PENDING = "FETCH_CONVERSIONS_PENDING";
export const FETCH_CONVERSIONS_SUCCESS = "FETCH_CONVERSIONS_SUCCESS";
export const FETCH_CONVERSIONS_ERROR = "FETCH_CONVERSIONS_ERROR";
