export const CLICK_CONVERT_VALUE = "CLICK_CONVERT_VALUE";

export const FETCH_SMS_PENDING = 'FETCH_SMS_PENDING';
export const FETCH_SMS_SUCCESS = 'FETCH_SMS_SUCCESS';
export const FETCH_SMS_ERROR = 'FETCH_SMS_ERROR';
