export const FETCH_CONVERT_PENDING = "FETCH_CONVERT_PENDING";
export const FETCH_CONVERT_SUCCESS = "FETCH_CONVERT_SUCCESS";
export const FETCH_CONVERT_ERROR = "FETCH_CONVERT_ERROR";

export const FETCH_SMS_PENDING = 'FETCH_SMS_PENDING';
export const FETCH_SMS_SUCCESS = 'FETCH_SMS_SUCCESS';
export const FETCH_SMS_ERROR = 'FETCH_SMS_ERROR';
